// Generated by scripts/generate-firebase-config.mjs — edit .env then run: npm run build
window.firebaseConfig = {
    "apiKey": "AIzaSyBujxLuLBTwJJ9RRnLGDr7Hl2CxANxWgbw",
    "authDomain": "raddad-sa.firebaseapp.com",
    "projectId": "raddad-sa",
    "storageBucket": "raddad-sa.firebasestorage.app",
    "messagingSenderId": "447411415246",
    "appId": "1:447411415246:web:9b5b24bc33034c3218c89f"
};
window.firebaseConfig.adminEmails = [
    "raddad@raddad.sa"
];
